Repository kubesphere-sigs/ks-versions, pull requests merged in 2021-12, with the labels that each got.

#14 Make ks-v0.0.60 as ready
  ks-v0.0.60.yaml
Labels: approved, size/XS, lgtm

#15 Create devops-agent-v3.2.0-rc.1.yaml for releasing devops-agent
  devops-agent-v3.2.0-rc.1.yaml
Labels: size/S, approved, lgtm

#16 Change the base branch from master to release-3.2 for the v3.2.1-rc.2
  ks-devops-v3.2.1-rc.2.yaml
Labels: approved, size/XS, lgtm

#17 release ks-devops v3.2.1-rc.2
  ks-devops-v3.2.1-rc.2.yaml
Labels: approved, size/XS, lgtm

#18 release ks-devops v3.2.1-rc.3
  ks-devops-v3.2.1-rc.3.yaml
Labels: approved, size/XS

#19 release kubekey-v1.2.1-rc.2
  installation/kubekey-v1.2.1-rc.2.yaml
Labels: approved, size/XS, lgtm

#20 release kubekey-v1.2.1-rc.3
  installation/kubekey-v1.2.1-rc.3.yaml
Labels: approved, size/XS, lgtm

#21 release ks-devops v3.2.1
  devops/ks-devops-v3.2.1.yaml
Labels: approved, size/XS, lgtm

#22 release kubekey-v1.2.1
  installation/kubekey-v1.2.1.yaml
Labels: approved, size/XS, lgtm

#23 release kubekey-v2.0.0-alpha.3
  installation/kubekey-v2.0.0-alpha.3.yaml
Labels: approved, size/XS, lgtm

#24 ready to release kubekey-v2.0.0-alpha.3
  installation/kubekey-v2.0.0-alpha.3.yaml
Labels: approved, size/XS, lgtm

#25 release kubekey-v2.0.0-alpha.4
  installation/kubekey-v2.0.0-alpha.4.yaml
Labels: approved, size/XS, lgtm
