Repository kubesphere-sigs/ks-versions, pull requests merged in 2021-11, with the labels that each got.

#1 Add the initial ks-releaser config file
  OWNERS
  ks-releaser-v0.0.5.yaml
Labels: size/S

#3 release ks-releaser-v0.0.5.yaml
  ks-releaser-v0.0.5.yaml
Labels: approved, size/XS

#2 Add ks-releaser config for ks cli
  ks-v0.0.56.yaml
Labels: size/S, approved

#4 Create ks-releaser-v0.0.6.yaml
  ks-releaser-v0.0.6.yaml
Labels: approved

#5 release ks-releaser v0.0.7
  ks-releaser-v0.0.7.yaml
Labels: approved, size/XS

#6 release ks v0.0.57
  ks-v0.0.57.yaml
Labels: approved, size/XS

#7 release ks-releaser v0.0.8
  ks-releaser-v0.0.8.yaml
Labels: approved

#8 release ks-releaser v0.0.9
  ks-releaser-v0.0.9.yaml
Labels: approved, size/XS

#10 release ks v0.0.58
  ks-v0.0.58.yaml
Labels: approved, size/XS, lgtm

#9 Create ks-devops-v3.2.1.yaml
  ks-devops-v3.2.1-rc.1.yaml
Labels: size/S, approved, lgtm

#11 release kubekey v1.2.1-rc.1
  OWNERS
  kubekey-v1.2.1-rc.1.yaml
Labels: lgtm, size/M, do-not-merge/invalid-owners-file

#12 fix the secret of ks-versions
  kubekey-v1.2.1-rc.1.yaml
Labels: approved, size/XS

#13 release ks v0.0.59
  ks-v0.0.59.yaml
Labels: approved, size/XS, lgtm
