Repository kubesphere-sigs/ks-versions, pull requests merged in 2022-04, with the labels that each got.

#33 Add a draft for si2operator v3.2.1
  devops/s2ioperator.yaml
Labels: size/S, approved, lgtm

#34 Release s2ioperator v3.2.1
  devops/s2ioperator.yaml
Labels: size/XS, lgtm

#35 Fix the filename of si2operator yaml
  devops/s2ioperator-v3.2.1.yaml
Labels: approved, size/XS

#36 Create ks-devops-v3.3.0-alpha.0 in draft state
  devops/ks-devops-v3.3.0-alpha.0.yaml
Labels: size/S, approved, lgtm

#38 release ks-devops-v3.3.0-alpha.1
  devops/ks-devops-v3.3.0-alpha.1.yaml
Labels: approved, size/XS

#39 release kubekey-v2.1.0-alpha.1
  installation/kubekey-v2.1.0-alpha.0.yaml
  installation/kubekey-v2.1.0-alpha.1.yaml
Labels: size/S, approved, lgtm
